# settings for the training v0.1 pipeline

# dataset settings

experiment_name: 'train_v0.1'

paths:
  era5_norm_params_path: '/mnt/hdd/jetstream/data/processed/train_v0.1/norm/era5/'
  ecmwf_norm_params_path: '/mnt/hdd/jetstream/data/processed/train_v0.1/norm/ecmwf/'
  amdar_norm_params_path: '/mnt/hdd/jetstream/data/processed/train_v0.1/norm/amdar/'

  era5_load_path: '/mnt/hdd/jetstream/data/development/era5/july2019/reanalysis_2019_07/pressure/*/*/*.nc'
  ecmwf_load_path: '/mnt/hdd/jetstream/data/development/ecmwf/july_2019/ecmwf_forecast.nc'
  amdar_load_path: '/mnt/hdd/jetstream/data/development/ceda/july_2019/data.ceda.ac.uk/badc/ukmo-metdb/data/amdars_debug/*/*/*.csv'

  process_base: '/mnt/hdd/jetstream/data/processed/train_v0.1/datasets/'
  process_era5_path_base:  '/mnt/hdd/jetstream/data/processed/train_v0.1/datasets/era5/era5.nc'
  process_ecmwf_path_base: '/mnt/hdd/jetstream/data/processed/train_v0.1/datasets/ecmwf/ecmwf.nc'
  process_amdar_path_base: '/mnt/hdd/jetstream/data/processed/train_v0.1/datasets/amdar/'

settings:
  clear_dataset_save_dir_on_startup: true
  clear_norm_params_on_startup: true

# use small datasets in development, often by subsetting in time.
environment:
  small_ds: true
  tensorboard_log_dir: './tb'

training:
  num_epochs: 1
  batch_size: 16
  train_dates_pct: 0.8
  xy_resolution: 200 # number of grid points in xy plane
  z_resolution: 100 # vertical resolution in vertical plane
  xy_window_size_km: 200 # width and height of the input grid in kilometers
  z_window_size_km: 8 # vertical size of the input grid in kilometers
  z_min_km: 2 # minimum altitude of the input grid in kilometers
  time_window_secs: 3600 # 1 hour time window around each amdar observation to consider for model input
  random_shift_variance_km: 20

# model settings
model:
  likelihood: "lowrank"
  conv_arch: "unet-res"
  unet_channels: 
    - 4
    - 4
  unet_kernels: 5
  points_per_unit: 5

# control which steps of the pipeline to execute
execute:
  dataset_preprocessing: false

  preprocessing:
    era5: true
    ecmwf: true
    amdar: true

  train: true